### ISSUE TITLE
Add an option to load file preview at 100% of the file resolution by default

### ISSUE THREAD

**Issue by NaitorStudios** [mooflu/QuickLook.Plugin.WebViewPlus#1]
Hey, amazing work!
One thing that I would like to be added is a option to make it go 100% instead of max res for the preview window size, it's just that I preview a lot of pixel art and some images that must be seen in the original resolution and that would be good.
Also, while you're at it, if you could please add a nearest neighbor mode, it would be cool as well, perhaps you could do it like the SmartUpscale Chrome extension, where it uses nearest neighbor for 100, 200, 300x etc but uses bilinear for anything in between.

These would be very appreciated additions, perhaps I'll try learning a bit to add some stuff myself, but I don't have a lot of time for it right now...

Thank you for creating this!

**Comment by mooflu** [comment]
https://github.com/mooflu/QuickLook.Plugin.WebViewPlus/releases/tag/1.1.0
