### ISSUE TITLE
Can tools like highlight text and draw be added to the pdf viewer? #5

### ISSUE THREAD

**Issue by sidsharths1245** [mooflu/QuickLook.Plugin.WebViewPlus#11]
I was wondering if these tools can be added.

**Comment by mooflu** [comment]
Sorry, looks like WebView2 no longer supports this. See https://github.com/MicrosoftEdge/WebView2Announcements/issues/21

**Comment by mooflu** [comment]
Looks like more changes coming around Nov 2024. 
https://techcommunity.microsoft.com/t5/microsoft-edge-insider/microsoft-edge-and-adobe-partner-to-improve-the-pdf-experience/ba-p/3733481

> How will this change affect WebView2 users and applications?
> 
> The PDF experience for WebView2 users will be at parity with the current Microsoft Edge built-in PDF reader. The option to access paid Adobe Acrobat premium features will not be visible in the new PDF experience on WebView2. The unobtrusive Adobe brand mark will also not be visible in  WebView2.
> 
>
