### ISSUE TITLE
PHP syntax support

### ISSUE THREAD

**Issue by Van4kk** [mooflu/QuickLook.Plugin.WebViewPlus#3]
Will be added support for PHP ? 

PHP is a popular language, I think it will help a lot of people

**Comment by mooflu** [comment]
Sure. In the meantime, you can add it via the settings. Add "php" under "Extra file extensions".

**Comment by Van4kk** [comment]
> Sure. In the meantime, you can add it via the settings. Add "php" under "Extra file extensions".

Thank you!
