### ISSUE TITLE
garbage characters

### ISSUE THREAD

**Issue by Ignorant12321** [mooflu/QuickLook.Plugin.WebViewPlus#7]
Will be added support for  custom encoding format?
![image](https://github.com/mooflu/QuickLook.Plugin.WebViewPlus/assets/131669301/3179a71a-d036-41e5-8e19-c6e075176bd5)

**Comment by mooflu** [comment]
Added option to enable text file encoding detection in [1.4.0](https://github.com/mooflu/QuickLook.Plugin.WebViewPlus/releases/tag/1.4.0)
